trigger: none

pool:
  vmImage: ubuntu-latest

variables:
  terraformVersion: '1.10.5'
  workspaceName: 'dev'

stages:
  - stage: InstallTerraform
    jobs:
    - job: InstallTerraform
      steps:
        - task: TerraformInstaller@1
          inputs:
            terraformVersion: 'latest'

  - stage: TerraformInit
    jobs:
      - job: TerraformInit
        steps:
          - task: TerraformTaskV4@4
            inputs:
              provider: 'aws'
              command: 'init'
              backendServiceAWS: 'tod-aws-service-connection'
              backendAWSBucketName: 'tod-tf-state-store'
              backendAWSKey: 'terraform.tfstate'