trigger: none

pool:
  vmImage: ubuntu-latest

variables:
  terraformVersion: '1.10.5'
  workspaceName: 'dev'

stages:
  - stage: TerraformInitPlan
    jobs:
    - job: TerraformInitPlan
      steps:
        - task: ms-devlabs.custom-terraform-tasks.custom-terraform-installer-task.TerraformInstaller@0
          displayName: Install terraform
          inputs:
            terraformVersion: 1.10.0
        
        - task: AWSShellScript@1
          displayName: "Terraform init and plan"
          inputs:
            awsCredentials: 'tod-aws'
            regionName: 'us-east-1'
            scriptType: 'inline'
            inlineScript: |
              pwd
              ls -lrt
              terraform init
              terraform workspace select $(workspaceName) || terraform workspace new $(workspaceName)
              terraform plan --var-file=variables.tfvars
            
  - stage: TerraformInitApply
    jobs:
    - deployment: TerraformInitApply
      displayName: "Deploy infra"
      environment: tf-aws-ec2-linux-env
      strategy:
        runOnce:
          deploy:
            steps:
            - checkout: self
            - task: ms-devlabs.custom-terraform-tasks.custom-terraform-installer-task.TerraformInstaller@0
              displayName: "Install terraform"
              inputs:
                terraformVersion: 1.10.0
            
            - task: AWSShellScript@1
              displayName: "Terraform apply"
              inputs:
                awsCredentials: 'tod-aws'
                regionName: 'us-east-1'
                scriptType: 'inline'
                inlineScript: |
                  pwd
                  ls -lrt
                  terraform init
                  terraform workspace select $(workspaceName) || terraform workspace new $(workspaceName)
                  terraform apply --var-file=variables.tfvars --auto-approve

  - stage: TerraformDestroy
    jobs:
    - deployment: TerraformDestroy
      displayName: "Destroy infra"
      environment: tf-aws-ec2-linux-env
      strategy:
        runOnce:
          deploy:
            steps:
            - checkout: self
            - task: ms-devlabs.custom-terraform-tasks.custom-terraform-installer-task.TerraformInstaller@0
              displayName: "Install terraform"
              inputs:
                terraformVersion: 1.10.0
            
            - task: AWSShellScript@1
              displayName: "Terraform apply"
              inputs:
                awsCredentials: 'tod-aws'
                regionName: 'us-east-1'
                scriptType: 'inline'
                inlineScript: |
                  pwd
                  ls -lrt
                  terraform init
                  terraform workspace select $(workspaceName) || terraform workspace new $(workspaceName)
                  terraform destroy --var-file=variables.tfvars --auto-approve