trigger: none

pool:
  vmImage: ubuntu-latest

parameters:
  - name: target_env
    values:
      - par-np
      - par-prod

  - name: workspaceName

variables:
  - name: backendServiceAWS
    ${{ if eq( parameters.target_env, 'par-np')}}:
      value: "par-terraform-np"
    ${{ if eq( parameters.target_env, 'par-prod')}}:
      value: "par-terraform-prod"

stages:
  - stage: TerraformInitPlan
    jobs:
    - job: TerraformInitPlan
      steps:
        - task: TerraformInstaller@1
          displayName: 'Install terraform'
          inputs:
            terraformVersion: 'latest'

        - task: TerraformTask@5
          displayName: 'terraform init'
          inputs:
            provider: 'aws'
            command: 'init'
            backendServiceAWS: 'par-terraform-np'
            backendAWSBucketName: 'tod-tf-state-store'
            backendAWSKey: 'terraform.tfstate'
        
        - task: TerraformTask@5
          displayName: 'terraform plan'
          inputs:
            provider: 'aws'
            command: 'plan'
            commandOptions: '--var-file=variables.tfvars'
            environmentServiceNameAWS: '${{ variables.backendServiceAWS }}'
        - task: TerraformTask@5
          inputs:
            provider: 'aws'
            command: 'apply'
            commandOptions: '--var-file=variables.tfvars'
            environmentServiceNameAWS: '${{ variables.backendServiceAWS }}'