trigger: none

pool:
  vmImage: ubuntu-latest

variables:
  terraformVersion: '1.10.5'
  workspaceName: 'dev'

stages:
  - stage: TerraformWorkflow
    jobs:
    - job: InstallTerraform
      steps:
        - task: ms-devlabs.custom-terraform-tasks.custom-terraform-installer-task.TerraformInstaller@0
          displayName: Install terraform
          inputs:
            terraformVersion: 1.10.0

        - task: Bash@3
          inputs:
            targetType: 'inline'
            script: |
              pwd
              ls -lrt
              terraform init
              terraform plan --var-file=variables.tfvars