trigger: none

pool:
  vmImage: ubuntu-latest

variables:
  terraformVersion: '1.10.5'
  workspaceName: 'dev'

stages:
  - stage: TerraformWorkflow
    jobs:
    - job: InstallTerraform
      steps:
        - task: TerraformInstaller@1
          displayName: "Install Terraform"
          inputs:
            terraformVersion: 'latest'

        - task: TerraformTaskV4@4
          displayName: "Terraform init"
          inputs:
            provider: 'aws'
            command: 'init'
            backendServiceAWS: 'tod-aws-service-connection'
            backendAWSBucketName: 'tod-tf-state-store'
            backendAWSKey: 'terraform.tfstate'