trigger: none

pool:
  vmImage: ubuntu-latest

variables:
  terraformVersion: '1.10.5'
  workspaceName: 'dev'

stages:
  - stage: TerraformWorkflow
    jobs:
    - job: InstallTerraform
      steps:
        - task: TerraformInstaller@1
          displayName: "Install Terraform"
          inputs:
            terraformVersion: 'latest'

        - task: Bash@3
          inputs:
            targetType: 'inline'
            script: |
              pwd
              ls -lrt
              terraform init
              terraform plan --var-file=variables.tfvars